language: c
compiler:
 - clang
 - gcc
before_script:
 - sudo apt-get install libldns-dev
 - git clone git://github.com/jedisct1/libsodium.git
 - cd libsodium
 - git checkout 0.5.0
 - ./autogen.sh
 - ./configure --disable-dependency-tracking
 - sudo make install
 - sudo ldconfig
 - cd ..
 - ./autogen.sh
 - ./configure --disable-dependency-tracking --enable-plugins
script:
 - make
